/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculador;

/**
 *
 * @author USER
 */
public class CalGui extends javax.swing.JFrame {

    /**
     * Creates new form CalGui
     */
    public CalGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pow = new javax.swing.JButton();
        Cos = new javax.swing.JButton();
        siete7 = new javax.swing.JButton();
        cuatro4 = new javax.swing.JButton();
        uno1 = new javax.swing.JButton();
        perc = new javax.swing.JButton();
        Sqrt = new javax.swing.JButton();
        Sin = new javax.swing.JButton();
        och8 = new javax.swing.JButton();
        cinco5 = new javax.swing.JButton();
        dos2 = new javax.swing.JButton();
        cer0 = new javax.swing.JButton();
        Tan = new javax.swing.JButton();
        nueve9 = new javax.swing.JButton();
        sis6 = new javax.swing.JButton();
        tres3 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        divs = new javax.swing.JButton();
        Dele = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        rest = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora"));

        Pow.setBackground(new java.awt.Color(153, 153, 153));
        Pow.setText("Pow");
        Pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowActionPerformed(evt);
            }
        });

        Cos.setBackground(new java.awt.Color(153, 153, 153));
        Cos.setText("Cos");
        Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosActionPerformed(evt);
            }
        });

        siete7.setBackground(new java.awt.Color(255, 255, 255));
        siete7.setText("7");
        siete7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siete7ActionPerformed(evt);
            }
        });

        cuatro4.setBackground(new java.awt.Color(255, 255, 255));
        cuatro4.setText("4");
        cuatro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatro4ActionPerformed(evt);
            }
        });

        uno1.setBackground(new java.awt.Color(255, 255, 255));
        uno1.setText("1");
        uno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uno1ActionPerformed(evt);
            }
        });

        perc.setBackground(new java.awt.Color(255, 255, 255));
        perc.setText("%");
        perc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percActionPerformed(evt);
            }
        });

        Sqrt.setBackground(new java.awt.Color(153, 153, 153));
        Sqrt.setText("Sqrt");
        Sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtActionPerformed(evt);
            }
        });

        Sin.setBackground(new java.awt.Color(153, 153, 153));
        Sin.setText("Sin");
        Sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinActionPerformed(evt);
            }
        });

        och8.setBackground(new java.awt.Color(255, 255, 255));
        och8.setText("8");
        och8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                och8ActionPerformed(evt);
            }
        });

        cinco5.setBackground(new java.awt.Color(255, 255, 255));
        cinco5.setText("5");
        cinco5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinco5ActionPerformed(evt);
            }
        });

        dos2.setBackground(new java.awt.Color(255, 255, 255));
        dos2.setText("2");
        dos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dos2ActionPerformed(evt);
            }
        });

        cer0.setBackground(new java.awt.Color(255, 255, 255));
        cer0.setText("0");
        cer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cer0ActionPerformed(evt);
            }
        });

        Tan.setBackground(new java.awt.Color(153, 153, 153));
        Tan.setText("Tan");
        Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanActionPerformed(evt);
            }
        });

        nueve9.setBackground(new java.awt.Color(255, 255, 255));
        nueve9.setText("9");
        nueve9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve9ActionPerformed(evt);
            }
        });

        sis6.setBackground(new java.awt.Color(255, 255, 255));
        sis6.setText("6");
        sis6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sis6ActionPerformed(evt);
            }
        });

        tres3.setBackground(new java.awt.Color(255, 255, 255));
        tres3.setText("3");
        tres3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres3ActionPerformed(evt);
            }
        });

        jButton36.setBackground(new java.awt.Color(255, 255, 255));
        jButton36.setText(",");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        divs.setBackground(new java.awt.Color(153, 153, 153));
        divs.setText("/");
        divs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divsActionPerformed(evt);
            }
        });

        Dele.setBackground(new java.awt.Color(153, 153, 153));
        Dele.setText("Del");
        Dele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleActionPerformed(evt);
            }
        });

        mult.setBackground(new java.awt.Color(153, 153, 153));
        mult.setText("x");
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });

        rest.setBackground(new java.awt.Color(153, 153, 153));
        rest.setText("-");
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(153, 153, 153));
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(51, 153, 255));
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pantalla.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uno1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuatro4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siete7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cer0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dos2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinco5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(och8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tres3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sis6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueve9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rest, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dele, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(och8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(cinco5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(dos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(cer0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Dele, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(divs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(rest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(nueve9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(sis6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(tres3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Pow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(siete7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(cuatro4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(uno1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(perc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siete7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siete7ActionPerformed
       number=number+"7"; // TODO add your handling code here:
       pantalla.setText(number);
    }//GEN-LAST:event_siete7ActionPerformed

    private void percActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percActionPerformed
       op=10;
       seteo();// TODO add your handling code here:
    }//GEN-LAST:event_percActionPerformed

    private void och8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_och8ActionPerformed
       number=number+"8"; // TODO add your handling code here:
       pantalla.setText(number);
    }//GEN-LAST:event_och8ActionPerformed

    private void cinco5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinco5ActionPerformed
      number=number+"5";  // TODO add your handling code here:
      pantalla.setText(number);
    }//GEN-LAST:event_cinco5ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
      number=number+".";
      pantalla.setText(number);// TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void cer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cer0ActionPerformed
       number=number+"0"; // TODO add your handling code here: 
       pantalla.setText(number);
    }//GEN-LAST:event_cer0ActionPerformed

    private void uno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uno1ActionPerformed
       number=number+"1"; // TODO add your handling code here:
       pantalla.setText(number);
    }//GEN-LAST:event_uno1ActionPerformed

    private void cuatro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatro4ActionPerformed
      number=number+"4";  // TODO add your handling code here:
      pantalla.setText(number);
    }//GEN-LAST:event_cuatro4ActionPerformed

    private void SinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinActionPerformed
      op=6;
      pantalla.setText("Sin");  // TODO add your handling code here:
    }//GEN-LAST:event_SinActionPerformed

    private void dos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dos2ActionPerformed
     number=number+"2";   // TODO add your handling code here:
     pantalla.setText(number);
    }//GEN-LAST:event_dos2ActionPerformed

    private void tres3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres3ActionPerformed
     number=number+"3";   // TODO add your handling code here:
     pantalla.setText(number);
    }//GEN-LAST:event_tres3ActionPerformed

    private void sis6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sis6ActionPerformed
      number=number+"6";  // TODO add your handling code here:
      pantalla.setText(number);
    }//GEN-LAST:event_sis6ActionPerformed

    private void nueve9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve9ActionPerformed
      number=number+"9";  // TODO add your handling code here:
      pantalla.setText(number);
    }//GEN-LAST:event_nueve9ActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
      op=3;
      seteo();
// TODO add your handling code here:
    }//GEN-LAST:event_multActionPerformed

    private void DeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleActionPerformed
     number=""; 
     pantalla.setText(number);// TODO add your handling code here:
    }//GEN-LAST:event_DeleActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed

        if (op != 5 || op != 6 || op != 7 || op!=8){
            calc.setB(Double.parseDouble(number));
            number="";
            System.out.println(calc.getB());
        }  /*else{
            //num=Float.parseFloat(number);
            calc.setA(Float.parseFloat(number));
            number="";
            System.out.println(calc.getA());
        }*/
        switch(op){
            case 1:
                prev=calc.suma();
                pantalla.setText(Double.toString(prev));
                break;
            case 2:
                prev=calc.resta();
                pantalla.setText(Double.toString(prev));
                break;
            case 3:
                prev=calc.mult();
                pantalla.setText(Double.toString(prev));
                break;
            case 4:
                prev=calc.div();
                pantalla.setText(Double.toString(prev));
                break;
            case 5:
                System.out.println(calc.coseno());
                prev =calc.coseno();
                pantalla.setText(Double.toString(prev));
                break;
            case 6:
                prev =calc.seno();
                pantalla.setText(Double.toString(prev));
                break;
            case 7:
                prev =calc.tang();
                pantalla.setText(Double.toString(prev));
                break;
            case 8:
                prev=calc.raiz();
                pantalla.setText(Double.toString(prev));
                break;
            case 9:
                prev =calc.pot();
                pantalla.setText(Double.toString(prev));
                break;
            case 10:
                prev =calc.porc();
                pantalla.setText(Double.toString(prev));
                break;
        }// TODO add your handling code here:
        calc.setA(prev);
        op=0;
    }//GEN-LAST:event_equalActionPerformed

    private void divsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divsActionPerformed
      op=4;
      seteo();// TODO add your handling code here:
    }//GEN-LAST:event_divsActionPerformed

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
       op=2;
       seteo();// TODO add your handling code here:
    }//GEN-LAST:event_restActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
       op=1;
       seteo();
        // TODO add your handling code here:
    }//GEN-LAST:event_plusActionPerformed

    private void CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosActionPerformed
       op=5;
       pantalla.setText("Cos");// TODO add your handling code here:
    }//GEN-LAST:event_CosActionPerformed

    private void TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanActionPerformed
      op=7;
       pantalla.setText("Tan"); // TODO add your handling code here:
    }//GEN-LAST:event_TanActionPerformed

    private void PowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowActionPerformed
       op=9;
       seteo();// TODO add your handling code here:
    }//GEN-LAST:event_PowActionPerformed

    private void SqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtActionPerformed
      op=8;
      pantalla.setText("Sqrt");// TODO add your handling code here:
    }//GEN-LAST:event_SqrtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalGui().setVisible(true);
            }
        });
    }
    public String number="";
    public int op =0;
    public double prev, num;
    calculadora calc=new calculadora();
    
    public void seteo(){
        calc.setA(Double.parseDouble(number));
        number="";
        pantalla.setText(number);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cos;
    private javax.swing.JButton Dele;
    private javax.swing.JButton Pow;
    private javax.swing.JButton Sin;
    private javax.swing.JButton Sqrt;
    private javax.swing.JButton Tan;
    private javax.swing.JButton cer0;
    private javax.swing.JButton cinco5;
    private javax.swing.JButton cuatro4;
    private javax.swing.JButton divs;
    private javax.swing.JButton dos2;
    private javax.swing.JButton equal;
    private javax.swing.JButton jButton36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mult;
    private javax.swing.JButton nueve9;
    private javax.swing.JButton och8;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton perc;
    private javax.swing.JButton plus;
    private javax.swing.JButton rest;
    private javax.swing.JButton siete7;
    private javax.swing.JButton sis6;
    private javax.swing.JButton tres3;
    private javax.swing.JButton uno1;
    // End of variables declaration//GEN-END:variables
}
